import { chromium } from "@playwright/test";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const p = await c.newPage();
await p.goto("http://localhost:3100/login"); await p.fill('input[type="password"]', "dev"); await p.keyboard.press("Enter");
await p.waitForURL("http://localhost:3100/"); await p.waitForTimeout(2000);
await p.locator(".fresh-tabbar button", { hasText: "Recipes" }).click(); await p.waitForTimeout(700);
await p.screenshot({ path: "smoke/out/peek-recipes.png" });
await p.locator(".fresh-tabbar button", { hasText: "Expenses" }).click(); await p.waitForTimeout(500);
await p.getByRole("button", { name: "Month" }).click(); await p.waitForTimeout(700);
await p.mouse.wheel(0, 1500); await p.waitForTimeout(400);
await p.screenshot({ path: "smoke/out/peek-month.png" });
await b.close();
